sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dockyog/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockyog/react-test npm test

after_success:
  - docker build -t dockyog/multi-client ./client
  - docker build -t dockyog/multi-nginx ./nginx
  - docker build -t dockyog/multi-server ./server
  - docker build -t dockyog/multi-worker ./worker
  # Login in to the docker CLI
  # Take those images and push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dockyog/multi-client
  - docker push dockyog/multi-nginx
  - docker push dockyog/multi-server
  - docker push dockyog/multi-worker